version: '3.8'

services:
  notification-service:
    image: harshithakkapelli/notification-service:v1
    ports:
      - "8098:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}

