apiVersion: v1
kind: Service
metadata:
  name: recommendation-api
  labels:
    app: recommendation-service
spec:
  type: ClusterIP
  selector:
    component: recommendation-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
