version: "3.8"

services:
  api:
    image: neeharikasingh/rms-api:0.2
    ports:
      - "8000:8000"
    env_file: .env
    restart: unless-stopped

  trainer:
    image: neeharikasingh/rms-trainer:0.2
    env_file: .env
    restart: "no"
