# Dockerfile.trainer
FROM python:3.10-slim

WORKDIR /app

# Install system build tools required by scikit-surprise
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libpython3-dev \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .


ENV PYTHONPATH=/app

# Train the model
CMD ["python", "recommender/train_model.py"]
