apiVersion: v1
kind: Service
metadata:
  name: geodishdiscovery-service
  labels:
    app: geodishdiscovery-service
spec:
  type: ClusterIP
  selector:
    app: geodishdiscovery-service
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
