apiVersion: v1
kind: Service
metadata:
  name: rating-service
  labels:
    app: rating-service
spec:
  type: ClusterIP
  selector:
    app: rating-service
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
