apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx-api-gateway
data:
  nginx.conf: |
    events {}
    http {
      include       mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" $request_time';

      access_log  /var/log/nginx/access.log  main;
      error_log   /var/log/nginx/error.log warn;

      server {
        listen 8080;

        location /dishmanagement/ {
          proxy_pass http://dishmanagement-service.default.svc.cluster.local:8080/;
        }

        location /geodishdiscovery/ {
          proxy_pass http://geodishdiscovery-service.default.svc.cluster.local:9091/;
        }

        location /notification/ {
          proxy_pass http://notification-service.default.svc.cluster.local:8080/;
        }

        location /order/ {
          proxy_pass http://order-service.default.svc.cluster.local:8008/;
        }

        location /rating/ {
          proxy_pass http://rating-service.default.svc.cluster.local:8090/;
        }

        location /recommendation/ {
          proxy_pass http://recommendation-api.default.svc.cluster.local:8000/;
        }

        location /user/ {
          proxy_pass http://user-service.default.svc.cluster.local:9000/;
        }

        location / {
          add_header Content-Security-Policy "default-src * data:; script-src * 'unsafe-inline'; style-src * 'unsafe-inline'";
          return 404;
        }
      }
    }
