apiVersion: v1
kind: Service
metadata:
  name: nginx-api-gateway
  labels:
    app: nginx-api-gateway
spec:
  type: NodePort
  selector:
    app: nginx-api-gateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
