apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include mime.types;
      log_format my_format '$remote_addr - $remote_user [$time_local] "$request" '
                                                        '$status $body_bytes_sent "$http_referer" '
                                                        '"$http_user_agent" $request_time';


      access_log /var/log/nginx/access.log my_format;
      error_log /var/log/nginx/error.log warn;
      server {
        listen 8080;
        location /auth/ {
            proxy_pass http://auth-app-service.default.svc.cluster.local:8098/auth/;
        }
        location /users {
            proxy_pass http://upm-app-service.default.svc.cluster.local:8088/users;
        }
        location /user-products/ {
            proxy_pass http://ups-app-service.default.svc.cluster.local:8082/user-products/;
        }
        location / {
            add_header Content-Security-Policy "default-src * data:; script-src * 'unsafe-inline'; style-src * 'unsafe-inline'";
            index index.html;
            try_files $uri $uri/ /index.html;
        }
      }
      
    }
