version: '3.8'

services:
  app:
    image: neeharikasingh/dms-app:6.0
    container_name: dish_management_service
    restart: always
    env_file:
      - dms.env  # Load secrets from an external environment file
    ports:
      - "${APP_PORT}:8080"
