version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rating_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rating-service:
    image: venkatesh1226m/kairos-rating-service:v2
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: rating_service
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_NOTIFICATION_TOPIC: ${KAFKA_NOTIFICATION_TOPIC}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: >
      sh -c "psql $DATABASE_URL -f /root/migrations/000001_create_rating_table.up.sql && ./rating-service"

volumes:
  pgdata:
