apiVersion: v1
kind: Service
metadata:
  name: dishmanagement-service
  labels:
    app: dishmanagement-service
spec:
  type: ClusterIP
  selector:
    app: dishmanagement-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
