// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Rating struct {
	ID         int32            `json:"id"`
	DishID     int32            `json:"dishId"`
	UserID     int32            `json:"userId"`
	Rating     pgtype.Int4      `json:"rating"`
	ReviewText pgtype.Text      `json:"reviewText"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}
