// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Rating struct {
	ID         int32            `json:"id"`
	DishID     string           `json:"dishId"`
	ChefID     string           `json:"chefId"`
	UserID     string           `json:"userId"`
	Rating     pgtype.Int4      `json:"rating"`
	ReviewText pgtype.Text      `json:"reviewText"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}
