version: "3.8"

services:
  userservice:
    image: harshithakkapelli/userservice:v2
    ports:
      - "9000:9000"
    environment:
      DB_URI: ${DB_URI}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}

