apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: harshithakkapelli/notification-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MONGO_URI
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: KAFKA_USERNAME
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: KAFKA_PASSWORD
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: KAFKA_BOOTSTRAP
